# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: Buildandpushdocker.
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Dev
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: gitclone 
    run: git clone https://github.com/Shubhambawa98/testenv.git
    - name: docker installation
    run: curl -fsSL https://get.docker.com | sh
    - name: docker login
    run: docker login -u ${{secrets.dockerhubusername}} -p $ {{sectets.dockerhubpassword}}
    - name: docker build
    run: cd testenv && docker build. -t fast_api:satyam
    - name: test
    run: echo "hello"
    -name: docker tag & push
    run: docker tag fast_api:satyam shubhambawa98/testlkm:satyam && docker push shubhambawa98/testlkm:satyam


